### ISSUE TITLE
session.get_pages() can't handle parameters

### ISSUE THREAD

**Issue by jon-magnus-moen-4ss** [4Subsea/fourinsight-api-python#35]
While trying the endpoint for EngineRoom applications, I I tried using the filter to get only a set of the applications. This failed after the first odata page, and after some testing, @ace-e4s and I found that it looks like the function sends parameters double when following the nextLink (both in the url and in **kwargs).

Example:
```
response = session.get_pages(
    "https://api.4insight.io/v1.0/Applications",
    params = {
        "$filter": "contains(name, '- vessel motions -')"
    }
)
for page in response:
    print(page.ok)
```
This returns true for first page and false for next page. Making a separate request to the nextLink provided by the response works fine.

**Comment by ace-e4s** [comment]
Fix in https://github.com/4Subsea/fourinsight-api-python/pull/36

**Comment by ace-e4s** [comment]
fix released
